### ISSUE TITLE
✨ Make icons to create files and folders

### ISSUE THREAD

**Issue by aleksandr-konovalov** [ordo-pink/ordo-electron#142] opened 2022-10-14 12:06 UTC
### What is it you truly desire

I now remembered for 10 minutes how to create a file, until I remembered that I had to right-click

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by orlowdev** [comment] 2022-10-28 16:19
This looks like a duplicate of #145. Closing it as such

**Closed by orlowdev** 2022-10-28 16:19 UTC
Labels: :sparkles: enhancement
